
namespace Bmg.Desafio.Contratacao.Domain.Aggregates.ContratacaoAgg.Queries.Models;

using Core.Api.Queries;

public partial class ContratoQueryModel : BaseQueryModel {
		///<summary>Id da proposta aprovada usada como origem.</summary>
		public int? PropostaIdEqual { get; set; }
		public int? PropostaIdNotEqual { get; set; }
		public int[]? PropostaIdContains { get; set; }
		public int[]? PropostaIdNotContains { get; set; }
		public int? PropostaIdSince { get; set; }
		public int? PropostaIdUntil { get; set; }
		public int? PropostaIdLessThan { get; set; }
		public int? PropostaIdGreaterThan { get; set; }
		public int? PropostaIdLessThanOrEqual { get; set; }
		public int? PropostaIdGreaterThanOrEqual { get; set; }
		///<summary>Número legível do contrato.</summary>
		public string? NumeroContratoEqual { get; set; }
		public string? NumeroContratoNotEqual { get; set; }
		public string? NumeroContratoContains { get; set; }
		public string? NumeroContratoNotContains { get; set; }
		public string? NumeroContratoStartsWith { get; set; }
		///<summary>Data em que a contratação foi efetivada.</summary>
		public System.DateTime? DataContratacaoEqual { get; set; }
		public System.DateTime? DataContratacaoNotEqual { get; set; }
		public System.DateTime[]? DataContratacaoContains { get; set; }
		public System.DateTime[]? DataContratacaoNotContains { get; set; }
		public System.DateTime? DataContratacaoSince { get; set; }
		public System.DateTime? DataContratacaoUntil { get; set; }
		public System.DateTime? DataContratacaoLessThan { get; set; }
		public System.DateTime? DataContratacaoGreaterThan { get; set; }
		public System.DateTime? DataContratacaoLessThanOrEqual { get; set; }
		public System.DateTime? DataContratacaoGreaterThanOrEqual { get; set; }
		///<summary>Início da vigência (mantido porque Specifications usam).</summary>
		public System.DateTime? InicioVigenciaEqual { get; set; }
		public System.DateTime? InicioVigenciaNotEqual { get; set; }
		public System.DateTime[]? InicioVigenciaContains { get; set; }
		public System.DateTime[]? InicioVigenciaNotContains { get; set; }
		public System.DateTime? InicioVigenciaSince { get; set; }
		public System.DateTime? InicioVigenciaUntil { get; set; }
		public System.DateTime? InicioVigenciaLessThan { get; set; }
		public System.DateTime? InicioVigenciaGreaterThan { get; set; }
		public System.DateTime? InicioVigenciaLessThanOrEqual { get; set; }
		public System.DateTime? InicioVigenciaGreaterThanOrEqual { get; set; }
		///<summary>Fim da vigência (mantido porque Specifications usam).</summary>
		public System.DateTime? FimVigenciaEqual { get; set; }
		public System.DateTime? FimVigenciaNotEqual { get; set; }
		public System.DateTime[]? FimVigenciaContains { get; set; }
		public System.DateTime[]? FimVigenciaNotContains { get; set; }
		public System.DateTime? FimVigenciaSince { get; set; }
		public System.DateTime? FimVigenciaUntil { get; set; }
		public System.DateTime? FimVigenciaLessThan { get; set; }
		public System.DateTime? FimVigenciaGreaterThan { get; set; }
		public System.DateTime? FimVigenciaLessThanOrEqual { get; set; }
		public System.DateTime? FimVigenciaGreaterThanOrEqual { get; set; }
		///<summary>Status atual do contrato.</summary>
		public Bmg.Desafio.Contratacao.Enumerations.ContratoStatus? StatusEqual { get; set; }
		///<summary>Motivo de cancelamento (se Status = Cancelado).</summary>
		public string? MotivoCancelamentoEqual { get; set; }
		public string? MotivoCancelamentoNotEqual { get; set; }
		public string? MotivoCancelamentoContains { get; set; }
		public string? MotivoCancelamentoNotContains { get; set; }
		public string? MotivoCancelamentoStartsWith { get; set; }
		///<summary>Data de cancelamento (se cancelado).</summary>
		public System.DateTime? DataCancelamentoEqual { get; set; }
		public System.DateTime? DataCancelamentoNotEqual { get; set; }
		public System.DateTime[]? DataCancelamentoContains { get; set; }
		public System.DateTime[]? DataCancelamentoNotContains { get; set; }
		public System.DateTime? DataCancelamentoSince { get; set; }
		public System.DateTime? DataCancelamentoUntil { get; set; }
		public System.DateTime? DataCancelamentoLessThan { get; set; }
		public System.DateTime? DataCancelamentoGreaterThan { get; set; }
		public System.DateTime? DataCancelamentoLessThanOrEqual { get; set; }
		public System.DateTime? DataCancelamentoGreaterThanOrEqual { get; set; }
		public int? UserIdEqual { get; set; }
		public int? UserIdNotEqual { get; set; }
		public int[]? UserIdContains { get; set; }
		public int[]? UserIdNotContains { get; set; }
		public int? UserIdSince { get; set; }
		public int? UserIdUntil { get; set; }
		public int? UserIdLessThan { get; set; }
		public int? UserIdGreaterThan { get; set; }
		public int? UserIdLessThanOrEqual { get; set; }
		public int? UserIdGreaterThanOrEqual { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdNotContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? DeletadoEqual { get; set; }
	}
